version: '3.8'

services:
  # 1. Spring Boot 서비스
  app:
    # 이미지 주소는 실제 본인의 주소로 직접 적어주시는 게 가장 확실합니다.
    image: ghcr.io/prgrms-be-devcourse/devstagram-backend:latest
    container_name: devstagram-app
    network_mode: host
    restart: always
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - JWT_SECRET
      - JWT_EXPIRE

  # 2. Nginx 서비스
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: host
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app