version: '3.8'
services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: local-db
    restart: always
    environment:
      POSTGRES_DB: devstagram
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./init-data:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d devstagram"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: local-redis
    ports:
      - "6379:6379"