spring:
  datasource:
    # GitHub Actions에서 넘겨주는 변수명과 매칭
    url: jdbc:postgresql://${RDS_HOSTNAME}:5432/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 운영 환경에서는 보통 update 또는 none을 사용합니다.
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

storage:
  # EC2 내부 경로
  location: ${STORAGE_PATH:/home/ec2-user/uploads}