spring:
  profiles:
    active: dev
  config:
    import: optional:file:./backend/devstagram/.env[.properties]


    servlet:
      multipart:
        enabled: true
        max-file-size: 50MB      # 파일 업로드 시 하나당 최대 용량
        max-request-size: 50MB   # 전체 요청당 최대 용량

server:
  port: 8080

storage:
  location: ${STORAGE_PATH:./uploads}
  # .env에 본인의 로컬 프로젝트 파일 경로 STORAGE_PATH 설정

custom:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expire-seconds: ${JWT_ACCESS_TOKEN_EXPIRE_SECONDS}