spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devstagram_test
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.jdbc.types_sql_type_mapping: true
        hibernate.type.preferred_array_jdbc_type: VECTOR
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

custom:
  jwt:
    secret-key: "test_secret_key_for_devstagram_project_at_least_32_chars"
    access-token-expire-seconds: 3600