name: Checkstyle

on:
  pull_request:
    branches: [ main, develop ] # PR 대상 브랜치

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: ./backend/back

      - name: Run Gradle Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest --build-cache
        working-directory: backend/back
